version: '3'

services:

    rabbitmq:
        container_name: rabbitmq
        build: .
        image: rabbitmq:management
        hostname: rabbitmq
        network_mode: default
        deploy:
            resources:
                limits:
                    cpus: "0.1"
                    memory: 1G
            restart_policy:
                condition: on-failure
        ports:
            - "8080:15672"
            - "5672:5672"
